In [ ]:
import numpy as np
import pandas as pd

#Warangal
def gdp1(**kwargs):
    """
    Transforms GDP data into the desired format

    Arguments required:
    1. 'df' type pandas.DataFrame
    2. 'rows' type list (optional)

    Returns:
    1. DataFrame
    """
    wardid = kwargs['wardid']
    cityid = kwargs['cityid']
    
    if 'df' in kwargs:
        df = kwargs['df']

        gdp_cols = [2,3,64,65,66,67,68,69,70,71,72]
        df = df[df.columns[gdp_cols]]

        if 'rows' in kwargs:
            df = df.head(kwargs['rows'])

        col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
               'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
               'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
               'Community Social Public Admin':9}

        df = df.rename(columns=col_map)
        df = df[['City','Ward No.',1,2,3,4,5,6,7,8,9]]
        df = df[df.columns[2:11]]

        ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
        ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
        ar_cnt_est = np.resize(100, len(ar_gdp))
        ar_cityid = np.resize(cityid, len(ar_gdp))
        ar_wardid = np.repeat(range(wardid.iat[0,0]+1,wardid.iat[0,0]+int((len(ar_gdp))/36)+1),36)

        quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
        quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)

        gdp_form = pd.DataFrame({'cityid':ar_cityid,'wardid':ar_wardid,'sectorcode':ar_sec,
                                 'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

        gdp_form['quarter'] = quarter
        gdp_form = gdp_form[['cityid','wardid','sectorcode','quarter','gdp','cnt_esta']]

        return gdp_form
    
    else:
        print('Argument required:  \'df\' type pandas.DataFrame')

#Karimnagar
def gdp2(**kwargs):
    """
    Transforms GDP data into the desired format

    Arguments required:
    1. 'df' type pandas.DataFrame
    2. 'rows' type list (optional)

    Returns:
    1. DataFrame
    """
    wardid = kwargs['wardid']
    cityid = kwargs['cityid']
    
    if 'df' in kwargs:
        df = kwargs['df']

        gdp_cols = [2,3,64,65,66,67,68,69,70,71,72]
        df = df[df.columns[gdp_cols]]

        if 'rows' in kwargs:
            df = df.head(kwargs['rows'])

        col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
               'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
               'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
               'Community Social Public Admin':9}

        df = df.rename(columns=col_map)
        df = df[['City','Ward',1,2,3,4,5,6,7,8,9]]
        df = df[df.columns[2:11]]

        ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
        ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
        ar_cnt_est = np.resize(100, len(ar_gdp))
        ar_cityid = np.resize(cityid, len(ar_gdp))
        ar_wardid = np.repeat(range(wardid.iat[0,0]+1,wardid.iat[0,0]+int((len(ar_gdp))/36)+1),36)

        quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
        quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)

        gdp_form = pd.DataFrame({'cityid':ar_cityid,'wardid':ar_wardid,'sectorcode':ar_sec,
                                 'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

        gdp_form['quarter'] = quarter
        gdp_form = gdp_form[['cityid','wardid','sectorcode','quarter','gdp','cnt_esta']]

        return gdp_form
    
    else:
        print('Argument required:  \'df\' type pandas.DataFrame')
        
#Rajasthan
def gdp3(**kwargs):
    """
    Transforms GDP State data into desired format

    Arguments required:
    1. 'df' type pandas.DataFrame
    2. 'rows' type list (optional)

    Returns:
    1. DataFrame
    """
    
    
    if 'df' in kwargs:
        df = kwargs['df']
        
        if 'rows' in kwargs:
            df = df.head(kwargs['rows'])
        
        stateid = df['stateid']
        cityid = pd.DataFrame(df['cityid'])
        if int(cityid.isnull().sum()) > 0:
            
            if 'max_cityid' in kwargs:
                
                cityid_max = kwargs['max_cityid']
                stateid = stateid.fillna(value=stateid.dropna()[0])        
                cityid.loc[cityid.cityid.isnull(), 'cityid'] = np.repeat(range(cityid_max.iat[0,0]+1,cityid_max.iat[0,0]+int(cityid.isnull().sum())+1),1).tolist()
                cityid = cityid.iloc[:,0]
                
            else:
                print('Argument required:  \'max_cityid\' type pandas.DataFrame')
                return 0
                
        gdp_cols = [2,3,64,65,66,67,68,69,70,71,72]
        df = df[df.columns[gdp_cols]]

        col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
               'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
               'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
               'Community Social Public Admin':9}

        df = df.rename(columns=col_map)
        df = df[[1,2,3,4,5,6,7,8,9]]

        ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
        ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
        ar_cnt_est = np.resize(100, len(ar_gdp))
        ar_stateid = np.resize(stateid, len(ar_gdp))
        ar_cityid = np.repeat(cityid,36)

        quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
        quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)
        
        ar_quarter = quarter.to_numpy().flatten()
        
        gdp_form = pd.DataFrame({'stateid':ar_stateid,'cityid':ar_cityid,'sectorcode':ar_sec,
                                 'quarter':ar_quarter,'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

        return gdp_form
    
    else:
        print('Argument required:  \'df\' type pandas.DataFrame')
        
#Lucknow        
def gdp4(**kwargs):
    """
    Transforms GDP State data into desired format

    Arguments required:
    1. 'df' type pandas.DataFrame
    2. 'rows' type list (optional)

    Returns:
    1. DataFrame
    """
    
    wardid = kwargs['wardid']
    cityid = kwargs['cityid']
    
    if 'df' in kwargs:
        df = kwargs['df']
        
        if 'rows' in kwargs:
            df = df.head(kwargs['rows'])
        
                
        gdp_cols = [2,63,64,65,66,67,68,69,70,71]
        df = df[df.columns[gdp_cols]]

        col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
               'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
               'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
               'Community Social Public Admin':9}

        df = df.rename(columns=col_map)
        df = df[['Ward Number',1,2,3,4,5,6,7,8,9]]
        df = df[df.columns[1:10]]

        ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
        ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
        ar_cnt_est = np.resize(100, len(ar_gdp))
        ar_cityid = np.resize(cityid, len(ar_gdp))
        ar_wardid = np.repeat(range(wardid.iat[0,0]+1,wardid.iat[0,0]+int((len(ar_gdp))/36)+1),36)

        quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
        quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)

        gdp_form = pd.DataFrame({'cityid':ar_cityid,'wardid':ar_wardid,'sectorcode':ar_sec,'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

        gdp_form['quarter'] = quarter
        gdp_form = gdp_form[['cityid','wardid','sectorcode','quarter','gdp','cnt_esta']]

        return gdp_form
    
    else:
        print('Argument required:  \'df\' type pandas.DataFrame')


#Uttar Pradesh    
def gdp5(**kwargs):
    """
    Transforms GDP State data into desired format

    Arguments required:
    1. 'df' type pandas.DataFrame
    2. 'rows' type list (optional)

    Returns:
    1. DataFrame
    """
    
    
    if 'df' in kwargs:
        df = kwargs['df']
        
        if 'rows' in kwargs:
            df = df.head(kwargs['rows'])
        
        stateid = df['stateid']
        cityid = pd.DataFrame(df['cityid'])
        cityid = cityid['cityid']
        if int(cityid.isnull().sum()) > 0:
            
            if 'max_cityid' in kwargs:
                
                cityid_max = kwargs['max_cityid']
                stateid = stateid.fillna(value=stateid.dropna()[0])        
                cityid.loc[cityid.cityid.isnull(), 'cityid'] = np.repeat(range(cityid_max.iat[0,0]+1,cityid_max.iat[0,0]+int(cityid.isnull().sum())+1),1).tolist()
                cityid = cityid.iloc[:,0]
                
            else:
                print('Argument required:  \'max_cityid\' type pandas.DataFrame')
                return 0
                
        gdp_cols = [3,65,66,67,68,69,70,71,72,73]
        df = df[df.columns[gdp_cols]]

        col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
               'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
               'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
               'Community Social Public Admin':9}

        df = df.rename(columns=col_map)
        df = df[[1,2,3,4,5,6,7,8,9]]

        ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
        ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
        ar_cnt_est = np.resize(100, len(ar_gdp))
        ar_stateid = np.resize(stateid, len(ar_gdp))
        ar_cityid = np.repeat(cityid,36)

        quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
        quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)
        
        ar_quarter = quarter.to_numpy().flatten()
        
        gdp_form = pd.DataFrame({'stateid':ar_stateid,'cityid':ar_cityid,'sectorcode':ar_sec,
                                 'quarter':ar_quarter,'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

        return gdp_form
    
    else:
        print('Argument required:  \'df\' type pandas.DataFrame')

In [ ]:
import sqlalchemy
import pandas as pd
import numpy as np


class DBConnect:
    db_username = ''
    db_pwd = ''
    db_name = ''
    db_ip = ''
    database_connection = ''

    def __init__(self, db_username, db_pwd, db_name, db_ip):
        self.db_username = db_username
        self.db_pwd = db_pwd
        self.db_name = db_name
        self.db_ip = db_ip
        self.database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}?use_pure=True'.
                                                            format(db_username, db_pwd,
                                                                   db_ip, db_name))

    def exportDataFrametoMySQL(self, df, table_name, reset_index=False):
        if reset_index:
            df.reset_index().to_sql(con=self.database_connection, name=table_name, if_exists='replace', index=False)
        else:
            df.to_sql(con=self.database_connection, name=table_name, if_exists='replace', index=False)


db_username = 'admin'
db_pwd = 'Sapio2020'
db_name = 'covid19_uat'
db_ip = 'sapiocoviddb.crtzk0iiuo47.us-west-2.rds.amazonaws.com'
db_connect = DBConnect(db_username=db_username, db_pwd=db_pwd, db_name=db_name, db_ip=db_ip)

In [ ]:
#pip install --index-url https://test.pypi.org/simple/ --no-deps Sapio_DSS

### Lucknow

In [ ]:
cityid = pd.read_sql(('SELECT covid19_uat.func_get_cityid_from_citynm(\'Lucknow\');'),db_connect.database_connection)

wardid_max = pd.read_sql(('SELECT MAX(wardid) FROM covid19_uat.tran_eco_gdp_ward;'), db_connect.database_connection)
wardid_max.iat[0,0] = 428
wardid_max

In [ ]:
df = gdp4(df = df, cityid = cityid, wardid = wardid_max, rows = 112)

In [ ]:
df.to_csv('gdp.csv')

### Uttar Pradesh

In [ ]:
url = 'https://docs.google.com/spreadsheets/d/1RE_FdiukiZlkCAAV-7NODlKghPXWDEZHV5QK11iE_Kk/edit#gid=0'
url_sheet_no = 0

In [ ]:
df, wks_url = sp.gsheetpy.get_url_data(url = url, sheet_no = url_sheet_no, cred = path)

In [ ]:
cityid_max = pd.read_sql(('SELECT MAX(cityid) FROM covid19_uat.mas_city;'),
                     db_connect.database_connection)

mas_city = pd.read_sql(('SELECT * FROM covid19_uat.mas_city;'),
                     db_connect.database_connection)
mas_city = mas_city[mas_city['stateid']=='UP']
mas_city = mas_city.rename(columns={'citynm':'City'})
df = df.rename(columns={'District':'City'})
df = pd.merge(df,mas_city, on='City', how='left')

In [ ]:
#df[['City','cityid']].to_csv('merge.csv')

In [ ]:
df = gdp5(df = df, rows = 75, max_cityid = cityid_max)

In [ ]:
df.to_csv('up_gdp.csv')

### Indore

In [ ]:
cityid = pd.read_sql(('SELECT covid19_uat.func_get_cityid_from_citynm(\'Indore\');'),
                     db_connect.database_connection)
wardid_max = pd.read_sql(('SELECT MAX(wardid) FROM covid19_uat.tran_eco_gdp_ward;'),
                     db_connect.database_connection)

#df1 = gdp4(df = df, cityid = cityid, wardid = wardid_max, rows = 84)

### Rajasthan

In [ ]:
cityid_max = pd.read_sql(('SELECT MAX(cityid) FROM covid19_uat.mas_city;'),
                     db_connect.database_connection)

mas_city = pd.read_sql(('SELECT * FROM covid19_uat.mas_city;'),
                     db_connect.database_connection)
mas_city = mas_city[mas_city['stateid']=='RJ']
mas_city = mas_city.rename(columns={'citynm':'City'})
df = pd.merge(df,mas_city, on='City', how='left')

In [ ]:
df = sp.transform.gdp3(df = df, rows = 33, max_cityid = cityid_max)

### Workspace

In [ ]:
df = df.head(84)

col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
       'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
       'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
       'Community Social Public Admin':9} 

df = df.rename(columns=col_map)

In [ ]:
df = df[['City','Zone',1,2,3,4,5,6,7,8,9]]
df = df.groupby('Zone').agg(sum)
df = df[df.columns[2:11]]

In [ ]:


ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
ar_cnt_est = np.resize(100, len(ar_gdp))
ar_cityid = np.resize(cityid, len(ar_gdp))
ar_wardid = np.repeat(range(wardid.iat[0,0]+1,wardid.iat[0,0]+int((len(ar_gdp))/36)+1),36)

quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)

gdp_form = pd.DataFrame({'cityid':ar_cityid,'wardid':ar_wardid,'sectorcode':ar_sec,
                         'gdp':ar_gdp,'cnt_esta':ar_cnt_est})

gdp_form['quarter'] = quarter
gdp_form = gdp_form[['cityid','wardid','sectorcode','quarter','gdp','cnt_esta']]

#### UP Workspace

In [ ]:
df = df1

In [ ]:
df = df.head(rows)

stateid = df['stateid']
cityid = pd.DataFrame(df['cityid'])
cityid = cityid['cityid']

In [ ]:
if int(cityid.isnull().sum()) > 0:

    cityid_max = max_cityid
    stateid = stateid.fillna(value=stateid.dropna()[0])        
    cityid.loc[cityid.cityid.isnull(), 'cityid'] = np.repeat(range(cityid_max.iat[0,0]+1,cityid_max.iat[0,0]+int(cityid.isnull().sum())+1),1).tolist()
    cityid = cityid.iloc[:,0]

In [ ]:
type(cityid)

In [ ]:

gdp_cols = [3,65,66,67,68,69,70,71,72,73]
df = df[df.columns[gdp_cols]]

col_map = {'Agriculture and Food':1,'Mining':2,'Manufacturing':3,
       'Electricity Gas Water':4,'Construction':5,'Trade Hotels Restaurants':6,
       'Transport Storage Communication':7,'Financing Real Estate Business Services':8,
       'Community Social Public Admin':9}

df = df.rename(columns=col_map)
df = df[[1,2,3,4,5,6,7,8,9]]

In [ ]:
ar_gdp = np.repeat(df.to_numpy().flatten(), 4)
ar_sec = np.resize(np.repeat(np.array(list(range(1,10))), 4),len(ar_gdp))
ar_cnt_est = np.resize(100, len(ar_gdp))
ar_stateid = np.resize(stateid, len(ar_gdp))
ar_cityid = np.repeat(cityid,36)

In [ ]:
quarter = pd.DataFrame({'quarter':['qtr1','qtr2','qtr3','qtr4']})
quarter = pd.concat([quarter]*int(len(ar_gdp)/4), ignore_index=True)

ar_quarter = quarter.to_numpy().flatten()

gdp_form = pd.DataFrame({'stateid':ar_stateid,'cityid':ar_cityid,'sectorcode':ar_sec,
                         'quarter':ar_quarter,'gdp':ar_gdp,'cnt_esta':ar_cnt_est})